<?php
return array (
  0 => 
  array (
    0 => 
    array (
      't_id' => '1',
      't_name' => '电影',
      't_enname' => 'dianying',
      't_sort' => '1',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_downtemplate' => 'voddown.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '1,5,6,7,8,9,10,11',
    ),
    1 => 
    array (
      't_id' => '2',
      't_name' => '连续剧',
      't_enname' => 'lianxuju',
      't_sort' => '2',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_downtemplate' => 'voddown.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '2,12,13,14,15',
    ),
    2 => 
    array (
      't_id' => '3',
      't_name' => '综艺',
      't_enname' => 'zongyi',
      't_sort' => '3',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_downtemplate' => 'voddown.html',
      't_hide' => '0',
      't_union' => ',106_15,elailu_16,',
      'childids' => '3',
    ),
    3 => 
    array (
      't_id' => '4',
      't_name' => '动漫',
      't_enname' => 'dongman',
      't_sort' => '4',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_downtemplate' => 'voddown.html',
      't_hide' => '0',
      't_union' => ',106_3,',
      'childids' => '4',
    ),
    4 => 
    array (
      't_id' => '5',
      't_name' => '动作片',
      't_enname' => 'dongzuopian',
      't_sort' => '11',
      't_pid' => '1',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_downtemplate' => 'voddown.html',
      't_hide' => '0',
      't_union' => ',120_8,106_1,',
      'childids' => '5',
    ),
    5 => 
    array (
      't_id' => '6',
      't_name' => '喜剧片',
      't_enname' => 'xijupian',
      't_sort' => '12',
      't_pid' => '1',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_downtemplate' => 'voddown.html',
      't_hide' => '0',
      't_union' => ',106_4,',
      'childids' => '6',
    ),
    6 => 
    array (
      't_id' => '7',
      't_name' => '爱情片',
      't_enname' => 'aiqingpian',
      't_sort' => '13',
      't_pid' => '1',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_downtemplate' => 'voddown.html',
      't_hide' => '0',
      't_union' => ',106_6,',
      'childids' => '7',
    ),
    7 => 
    array (
      't_id' => '8',
      't_name' => '科幻片',
      't_enname' => 'kehuanpian',
      't_sort' => '14',
      't_pid' => '1',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_downtemplate' => 'voddown.html',
      't_hide' => '0',
      't_union' => ',106_5,',
      'childids' => '8',
    ),
    8 => 
    array (
      't_id' => '9',
      't_name' => '恐怖片',
      't_enname' => 'kongbupian',
      't_sort' => '14',
      't_pid' => '1',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_downtemplate' => 'voddown.html',
      't_hide' => '0',
      't_union' => ',106_8,',
      'childids' => '9',
    ),
    9 => 
    array (
      't_id' => '10',
      't_name' => '剧情片',
      't_enname' => 'juqingpian',
      't_sort' => '16',
      't_pid' => '1',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_downtemplate' => 'voddown.html',
      't_hide' => '0',
      't_union' => ',110_8,106_2,',
      'childids' => '10',
    ),
    10 => 
    array (
      't_id' => '11',
      't_name' => '战争片',
      't_enname' => 'zhanzhengpian',
      't_sort' => '17',
      't_pid' => '1',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_downtemplate' => 'voddown.html',
      't_hide' => '0',
      't_union' => ',106_7,',
      'childids' => '11',
    ),
    11 => 
    array (
      't_id' => '12',
      't_name' => '国产剧',
      't_enname' => 'guochanju',
      't_sort' => '21',
      't_pid' => '2',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_downtemplate' => 'voddown.html',
      't_hide' => '0',
      't_union' => ',106_11,',
      'childids' => '12',
    ),
    12 => 
    array (
      't_id' => '13',
      't_name' => '港台剧',
      't_enname' => 'gangtaiju',
      't_sort' => '22',
      't_pid' => '2',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_downtemplate' => 'voddown.html',
      't_hide' => '0',
      't_union' => ',xsdzycc_4,106_12,',
      'childids' => '13',
    ),
    13 => 
    array (
      't_id' => '14',
      't_name' => '日韩剧',
      't_enname' => 'rihanju',
      't_sort' => '23',
      't_pid' => '2',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_downtemplate' => 'voddown.html',
      't_hide' => '0',
      't_union' => ',106_14,',
      'childids' => '14',
    ),
    14 => 
    array (
      't_id' => '15',
      't_name' => '欧美剧',
      't_enname' => 'oumeiju',
      't_sort' => '24',
      't_pid' => '2',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_downtemplate' => 'voddown.html',
      't_hide' => '0',
      't_union' => ',106_13,',
      'childids' => '15',
    ),
  ),
  1 => 
  array (
    0 => 
    array (
      't_id' => '1',
      't_name' => '站内新闻',
      't_enname' => 'zhanneixinwen',
      't_sort' => '1',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'artlist.html',
      't_arttemplate' => 'art.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '1',
    ),
    1 => 
    array (
      't_id' => '2',
      't_name' => '娱乐动态',
      't_enname' => 'yuledongtai',
      't_sort' => '2',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'artlist.html',
      't_arttemplate' => 'art.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '2',
    ),
    2 => 
    array (
      't_id' => '3',
      't_name' => '八卦爆料',
      't_enname' => 'baguabaoliao',
      't_sort' => '3',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'artlist.html',
      't_arttemplate' => 'art.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '3',
    ),
    3 => 
    array (
      't_id' => '4',
      't_name' => '影片资讯',
      't_enname' => 'yingpianzixun',
      't_sort' => '4',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'artlist.html',
      't_arttemplate' => 'art.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '4',
    ),
    4 => 
    array (
      't_id' => '5',
      't_name' => '明星资讯',
      't_enname' => 'mingxingzixun',
      't_sort' => '5',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'artlist.html',
      't_arttemplate' => 'art.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '5',
    ),
    5 => 
    array (
      't_id' => '6',
      't_name' => '电视资讯',
      't_enname' => 'dianshizixun',
      't_sort' => '6',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'artlist.html',
      't_arttemplate' => 'art.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '6',
    ),
  ),
  2 => 
  array (
    0 => 
    array (
      't_id' => '1',
      't_name' => 'aaaa',
      't_enname' => 'aaaa',
      't_sort' => '1',
      't_template' => 'aaaa',
      't_pic' => '',
      't_des' => 'aaaa',
    ),
    1 => 
    array (
      't_id' => '2',
      't_name' => 'bbb',
      't_enname' => 'bb',
      't_sort' => '2',
      't_template' => 'bbb',
      't_pic' => '',
      't_des' => 'bbb',
    ),
    2 => 
    array (
      't_id' => '3',
      't_name' => 'ccc',
      't_enname' => 'ccc',
      't_sort' => '3',
      't_template' => 'ccc',
      't_pic' => '',
      't_des' => 'ccc',
    ),
    3 => 
    array (
      't_id' => '4',
      't_name' => 'ddd',
      't_enname' => 'ddd',
      't_sort' => '4',
      't_template' => 'ddd',
      't_pic' => '',
      't_des' => 'ddd',
    ),
    4 => 
    array (
      't_id' => '5',
      't_name' => 'ccc',
      't_enname' => 'ccc',
      't_sort' => '5',
      't_template' => 'ccc',
      't_pic' => '',
      't_des' => 'ccc',
    ),
    5 => 
    array (
      't_id' => '6',
      't_name' => 'dddd',
      't_enname' => 'ddd',
      't_sort' => '6',
      't_template' => 'dddd',
      't_pic' => '',
      't_des' => 'ddd',
    ),
  ),
  3 => 
  array (
    0 => 
    array (
      't_id' => '1',
      't_name' => 'aaaaa',
      't_enname' => 'aaa',
      't_sort' => '2',
      't_template' => 'aaa.html',
      't_pic' => 'aaa.pic',
      't_des' => 'aaa',
    ),
    1 => 
    array (
      't_id' => '2',
      't_name' => 'bbbbb',
      't_enname' => 'bbb',
      't_sort' => '3',
      't_template' => 'bbb.html',
      't_pic' => 'bbb.pic',
      't_des' => 'bbb',
    ),
  ),
  4 => 
  array (
    0 => '大陆',
    1 => '香港',
    2 => '台湾',
    3 => '日本',
    4 => '韩国',
    5 => '美国',
    6 => '欧洲',
    7 => '亚洲',
    8 => '其他',
  ),
  5 => 
  array (
    0 => '﻿汉语',
    1 => '粤语',
    2 => '英语',
    3 => '日语',
    4 => '韩语',
  ),
  6 => 
  array (
    0 => 
    array (
      'ug_id' => '1',
      'ug_name' => '普通会员',
      'ug_type' => '',
      'ug_popedom' => '',
      'ug_upgrade' => '0',
      'ug_popvalue' => '1',
    ),
  ),
);
?>